version: '2'
services:
  bot:
    build:
      context: .
      dockerfile: ./Bot.Dockerfile
    depends_on:
      - db
    environment:
      MONGO_CONNECTION_URL: "mongodb://root:example@db:27017/admin?retryWrites=true&w=majority"
    volumes:
      - ../../bedpresChan:/srv/bedpresChan
    logging:
      options:
       max-size: "1g"
  db:
    image: mongo
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    logging:
      options:
       max-size: "1g"
