version: '2'
services:
  bot:
    build:
      context: .
      dockerfile: ./Bot.Dockerfile
    depends_on:
      - db
    environment:
      MONGO_CONNECTION_URL: "mongodb://root:example@db:27017/admin?retryWrites=true&w=majority"
#      DISCORD_WEBHOOK_URL: "https://canary.discordapp.com/api/webhooks/754074465083719820/bmu74r6rzHJqMoAvAjdGQAW7Z_FARlknbnKpLrusN1SJA38Amnh6BUbU6Z8ZcYWIogNR"
      DISCORD_TOKEN: NzYxNzQzNzc1NDI0NTc3NTg2.X3fDLA.5-toYHtSis9Q4FICIzV6BMGUePs
    volumes:
      - ../../bedpresChan:/srv/bedpresChan
    logging:
      options:
       max-size: "1g"
  db:
    image: mongo
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    logging:
      options:
       max-size: "1g"
